name: applicationinsights
description: AppInsights module for Nuxt.js
repo: nuxt-community/applicationinsights-module
npm: '@nuxtjs/applicationinsights'
icon: application-insights.png
github: 'https://github.com/nuxt-community/applicationinsights-module'
website: 'https://github.com/nuxt-community/applicationinsights-module'
learn_more: ''
released_at: '2020-12-17T19:49:03.091Z'
category: Analytics
type: community
maintainers:
  - name: Dmitry Molotkov
    github: aldarund
    avatar: 'https://avatars2.githubusercontent.com/u/571159?v=4'
