name: browserconfig
description: Adds XML browser configuration support
repo: nuxt-community/modules#master/packages/browserconfig
npm: '@nuxtjs/browserconfig'
icon: ''
github: https://github.com/nuxt-community/modules/tree/master/packages/browserconfig
website: https://github.com/nuxt-community/modules/tree/master/packages/browserconfig
learn_more: >-
  https://docs.microsoft.com/en-us/previous-versions/windows/internet-explorer/ie-developer/dev-guides/bg183312(v=vs.85)?redirectedfrom=MSDN
category: Extensions
type: community
maintainers:
  - name: Pooya Parsa
    github: pi0
    twitter: _pi0_
    avatar: https://avatars0.githubusercontent.com/u/5158436?v=4
