name: netlify-files
description: >-
  Nuxt module to create new _headers, _redirects and netlify.toml files for
  Netlify or to use existing ones
repo: nuxt-community/netlify-files-module
npm: '@nuxtjs/netlify-files'
icon: netlify.png
github: 'https://github.com/nuxt-community/netlify-files-module'
website: 'https://github.com/nuxt-community/netlify-files-module'
learn_more: 'https://www.netlify.com/'
released_at: '2020-05-28T16:15:48.452Z'
category: Deployment
type: community
maintainers:
  - name: Alexander Lichter
    github: manniL
    twitter: TheAlexLichter
    avatar: 'https://avatars0.githubusercontent.com/u/640208?v=4'
