name: netlify-files
description: >-
  Nuxt module to create new _headers, _redirects and netlify.toml files for
  Netlify or to use existing ones
repo: nuxt-community/netlify-files-module
npm: '@nuxtjs/netlify-files'
icon: netlify.png
github: https://github.com/nuxt-community/netlify-files-module
website: https://github.com/nuxt-community/netlify-files-module
learn_more: https://www.netlify.com/
category: Deployment
type: community
maintainers:
  - name: Alexander Lichter
    github: TheAlexLichter
    twitter: TheAlexLichter
    bluesky: thealexlichter.com
compatibility:
  nuxt: ^2.0.0
  requires: {}
