name: prometheus
description: >-
  Allows you to better understand what's going on with your application and how
  to optimize performance and other things in production
repo: artmizu/nuxt-prometheus
npm: '@artmizu/nuxt-prometheus'
icon: prometheus.svg
github: https://github.com/artmizu/nuxt-prometheus
website: https://github.com/artmizu/nuxt-prometheus
learn_more: ''
category: Monitoring
type: 3rd-party
maintainers:
  - name: Aleksandr Kriuchkov
    github: artmizu
compatibility:
  nuxt: ^2.16.0 || >=3.0.0
  requires: {}
